name: Build Ren'Py Game

on:
  push:
    branches:
      # Run this workflow on every push to the master branch
      - master

jobs:
  build:
    # Use a Linux runner (cheaper and usually faster)
    runs-on: ubuntu-latest

    env:
      RENPY_VERSION: "8.5.0"

    steps:
      - name: Checkout repository
        # Checkout the game project
        uses: actions/checkout@v4


      - name: Install pyenchant
        run: |
          sudo apt-get update && sudo apt-get install -y enchant-2
          pip install pyenchant

      - name: Validate project structure
        run: python3 validate.py
        
      - name: Build Renpy Project
        uses: ProjectAliceDev/renpy-build-action@master
        with:
          sdk-version: '8.5.0'
          project-dir: '.'
          package: 'win'
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy


      - name: Upload built distributions
        uses: actions/upload-artifact@v4
        with:
          name: the_question-build
          # The dist folder is created in the project directory (repo root)
          path: renpy-sdk/dist/**
